"""add validation engine columns

Revision ID: 54c64a6f369e
Revises: 63dba8f47fa1
Create Date: 2026-06-14 19:20:35.530286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54c64a6f369e'
down_revision: Union[str, Sequence[str], None] = '63dba8f47fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('validation_errors', sa.Column('row_number', sa.Integer(), nullable=True))
    op.add_column('validation_rules', sa.Column('column_name', sa.String(length=255), nullable=True))
    op.add_column('validation_rules', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_rules', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('validation_runs', sa.Column('total_records_checked', sa.Integer(), nullable=True))
    op.add_column('validation_runs', sa.Column('total_errors_found', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_runs', 'total_errors_found')
    op.drop_column('validation_runs', 'total_records_checked')
    op.drop_column('validation_rules', 'is_active')
    op.drop_column('validation_rules', 'params')
    op.drop_column('validation_rules', 'column_name')
    op.drop_column('validation_errors', 'row_number')
    op.drop_column('datasets', 'file_name')
    # ### end Alembic commands ###
